# Generated by Django 2.0.13 on 2020-06-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_id',
        ),
    ]
