# Generated by Django 3.0.7 on 2020-06-16 14:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_search_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='image',
        ),
        migrations.AlterField(
            model_name='boards',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
